USE [master]
GO

/****** Object:  Database [Employee_Management]    Script Date: 3/5/2020 11:43:47 PM ******/
CREATE DATABASE [Employee_Management]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Employee_Management', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Employee_Management.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Employee_Management_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Employee_Management_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Employee_Management].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Employee_Management] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Employee_Management] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Employee_Management] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Employee_Management] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Employee_Management] SET ARITHABORT OFF 
GO

ALTER DATABASE [Employee_Management] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Employee_Management] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Employee_Management] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Employee_Management] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Employee_Management] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Employee_Management] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Employee_Management] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Employee_Management] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Employee_Management] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Employee_Management] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Employee_Management] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Employee_Management] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Employee_Management] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Employee_Management] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Employee_Management] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Employee_Management] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Employee_Management] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Employee_Management] SET RECOVERY FULL 
GO

ALTER DATABASE [Employee_Management] SET  MULTI_USER 
GO

ALTER DATABASE [Employee_Management] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Employee_Management] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Employee_Management] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Employee_Management] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Employee_Management] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Employee_Management] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Employee_Management] SET  READ_WRITE 
GO


